### ISSUE TITLE
healthcheck status, get and update was return empty response

### ISSUE THREAD

**Issue by draskolnikova** [ZigzagAK/ngx_dynamic_healthcheck#2]
I've enable healthcheck status, but it return empty response. In error log it show.

```
2019/03/06 18:17:28 [notice] 9572#9572: dynamic upstream: background thread started
2019/03/06 18:17:33 [notice] 9326#9326: signal 17 (SIGCHLD) received from 9330
2019/03/06 18:17:33 [alert] 9326#9326: worker process 9330 exited on signal 11
2019/03/06 18:17:33 [notice] 9326#9326: start worker process 9574
2019/03/06 18:17:33 [notice] 9326#9326: signal 29 (SIGIO) received
2019/03/06 18:17:33 [notice] 9574#9574: dynamic upstream: background thread started
2019/03/06 18:17:37 [notice] 9326#9326: signal 17 (SIGCHLD) received from 9332
2019/03/06 18:17:37 [alert] 9326#9326: worker process 9332 exited on signal 11
2019/03/06 18:17:37 [notice] 9326#9326: start worker process 9576
2019/03/06 18:17:37 [notice] 9326#9326: signal 29 (SIGIO) received
2019/03/06 18:17:37 [notice] 9576#9576: dynamic upstream: background thread started
2019/03/06 18:17:37 [notice] 9326#9326: signal 17 (SIGCHLD) received from 9333
2019/03/06 18:17:37 [alert] 9326#9326: worker process 9333 exited on signal 11
2019/03/06 18:17:37 [notice] 9326#9326: start worker process 9578
2019/03/06 18:17:37 [notice] 9326#9326: signal 29 (SIGIO) received
2019/03/06 18:17:37 [notice] 9578#9578: dynamic upstream: background thread started
2019/03/06 18:17:37 [notice] 9326#9326: signal 17 (SIGCHLD) received from 9334
2019/03/06 18:17:37 [alert] 9326#9326: worker process 9334 exited on signal 11
2019/03/06 18:17:37 [notice] 9326#9326: start worker process 9580
2019/03/06 18:17:37 [notice] 9326#9326: signal 29 (SIGIO) received
```
I am using nginx 1.14.1. Is it expected?

**Comment by ZigzagAK** [comment]
@draskolnikova 
Please, send me full nginx configiration in archive.

**Comment by draskolnikova** [comment]
@ZigzagAK any emails?

**Comment by ZigzagAK** [comment]
@draskolnikova 
alkon2000@mail.ru

**Comment by draskolnikova** [comment]
@ZigzagAK email was sent.

**Comment by ZigzagAK** [comment]
@draskolnikova 
Module requires zone upstream directive.
Please, add zone shm_upstream_name 256k;

**Comment by ZigzagAK** [comment]
I will fix crash in next release when no zone directive is missing.

**Comment by draskolnikova** [comment]
@ZigzagAK I've add zone below upstream name with
```
upstream upstream_name {
    zone upstream_name 256k;
    server 172.16.89.17:28089 weight=20;
    server 172.16.89.18:28089 weight=20;
    server 172.16.89.21:28089 weight=20;
    server 172.16.89.22:28089 weight=20;
    server 172.16.89.23:28089 weight=20;

      check fall=1 rise=1 interval=5 timeout=15000 type=http;
      check_request_uri GET /healthz;
      check_request_body OK;
      check_response_body .*;
      check_response_codes 200 204;
}
```

Still got
```
2019/03/06 19:05:05 [alert] 23335#23335: worker process 23343 exited on signal 11
2019/03/06 19:05:05 [notice] 23335#23335: start worker process 23469
2019/03/06 19:05:05 [notice] 23335#23335: signal 29 (SIGIO) received
2019/03/06 19:05:05 [notice] 23469#23469: dynamic upstream: background thread started
2019/03/06 19:05:05 [notice] 23335#23335: signal 17 (SIGCHLD) received from 23342
2019/03/06 19:05:05 [alert] 23335#23335: worker process 23342 exited on signal 11
2019/03/06 19:05:05 [notice] 23335#23335: start worker process 23471
2019/03/06 19:05:05 [notice] 23335#23335: signal 29 (SIGIO) received
2019/03/06 19:05:05 [notice] 23471#23471: dynamic upstream: background thread started
```

**Comment by ZigzagAK** [comment]
I checked your configuration and everything is ok.

[aleksey@centos7 nginx-1.15.6]$ curl 'localhost:8080/healthcheck/status'
{
    "aleppo":{
        "primary":{
            "172.16.89.17:28089":{
                "down":1,
                "fall":2,
                "rise":0,
                "fall_total":2,
                "rise_total":0
            },
            "172.16.89.18:28089":{
                "down":1,
                "fall":2,
                "rise":0,
                "fall_total":2,
                "rise_total":0
            },
            "172.16.89.21:28089":{
                "down":1,
                "fall":2,
                "rise":0,
                "fall_total":2,
                "rise_total":0
            },
            "172.16.89.22:28089":{
                "down":1,
                "fall":2,
                "rise":0,
                "fall_total":2,
                "rise_total":0
            },
            "172.16.89.23:28089":{
                "down":1,
                "fall":2,
                "rise":0,
                "fall_total":2,
                "rise_total":0
            }
        }
    }
}
[aleksey@centos7 nginx-1.15.6]$ curl 'localhost:8080/healthcheck/get'
{
    "aleppo":{
        "rise":1,
        "fall":1,
        "interval":5,
        "keepalive":1,
        "timeout":15000,
        "type":"http",
        "port":0,
        "passive":0,
        "command":{
            "uri":"/healthz",
            "method":"GET",
            "headers":{},
            "body":"OK",
            "expected":{
                "body":".*",
                "codes":[200,204]
            }
        },
        "disabled":0,
        "off":0,
        "disabled_hosts":[],
        "excluded_hosts":[]
    }
}

May be other upstreams exists in your configuration?
Please, add zone directive in every upstream.

**Comment by ZigzagAK** [comment]
I use 1.15.6
Centos6/7
Build: build_with_lua.sh

**Comment by draskolnikova** [comment]
@ZigzagAK correct, there's hundreds upstreams outside that files. Trying to create single upstreams and it's normal. Hope in next release can show the error with error lines xD

Thanks mate.
