### ISSUE TITLE
Compatible state with vts and sts module

### ISSUE THREAD

**Issue by draskolnikova** [ZigzagAK/ngx_dynamic_healthcheck#3]
Hello!

Did your module compatible with https://github.com/vozlt/nginx-module-vts and https://github.com/vozlt/nginx-module-stream-sts ? I mean, the status update can be updated too when the host down / up?

It will useful to export the status to prometheus and grafana.

**Comment by ZigzagAK** [comment]
Hello, i am don't use this module.
My module change 'down' peer's flag, that declared in peer's structure, which allocated in shared memory. 
nginx-module-vts module also check 'fails'.
`usn.down = (peer->fails >= peer->max_fails || peer->down);`
This is a difference in output status between modules. 
ngx_dynamic_healthcheck change status on active healthcheck fails and don't use passive healthchecks (max_fails, fail_timeout). 

>It will useful to export the status to prometheus and grafana.

Yes. You may use status from ngx_dynamic_healthcheck.

**Comment by draskolnikova** [comment]
@ZigzagAK is it possible to patch vts module using ngx_dynamic_healthcheck method? Can you provides the snippet? Previously, I am using this patch https://github.com/vozlt/nginx-module-vts/pull/134/files

```
#if (NGX_HTTP_UPSTREAM_CHECK)
                if (ngx_http_upstream_check_peer_down(peer->check_index)) {
                    usn.down = 1;
                } else {
                    usn.down = 0;
                }
#else
```

**Comment by ZigzagAK** [comment]
You may simple remove passive check from condition:

```
#if (NGX_HTTP_UPSTREAM_CHECK)
               usn.down = peer->down;
#else
```

**Comment by draskolnikova** [comment]
@ZigzagAK so it will update the status same like on `fall` status from `/healthcheck/status` ? It means, if fall = 1, it means the status will mark upstream as `down`?

**Comment by ZigzagAK** [comment]
@draskolnikova 
No.
fall - current number of fails.
https://github.com/ZigzagAK/ngx_dynamic_healthcheck#check
If 'fall' from status API >= fall from 'check', then peer goes to down state ("down": 1).

**Comment by ZigzagAK** [comment]
Sorry,
>so it will update the status same like on fall status from /healthcheck/status

Yes. But in 'down' field.

**Comment by draskolnikova** [comment]
So, I just need patch vts/sts module with 
```
#if (NGX_HTTP_UPSTREAM_CHECK)
               usn.down = peer->down;
#else
```

And the status will change to down, if fail attempt >= fail from check. Isn't it?

**Comment by ZigzagAK** [comment]
Yes.

**Comment by ZigzagAK** [comment]
@draskolnikova 
Can I close this issue?

**Comment by draskolnikova** [comment]
@ZigzagAK I did't find any `NGX_HTTP_UPSTREAM_CHECK` in `ngx_dynamic_healthcheck`. Is it safe to compile?

**Comment by ZigzagAK** [comment]
@draskolnikova 
This define from https://github.com/yaoweibin/nginx_upstream_check_module/blob/master/config
Remove #if (NGX_HTTP_UPSTREAM_CHECK) and #endif absolutely. This define is not required for ngx_dynamic_healthcheck module.
Simple replace:
`usn.down = (peer->fails >= peer->max_fails || peer->down);`
with
`usn.down = peer->down;`

**Comment by draskolnikova** [comment]
@ZigzagAK solved, thanks m8.
