### ISSUE TITLE
check timeout, fall and rise do not honour the configurations

### ISSUE THREAD

**Issue by draskolnikova** [ZigzagAK/ngx_dynamic_healthcheck#4]
Hello!

I am using this confihguration for healthcheck.

```
    check fall=3 rise=1 interval=1 timeout=5 type=http;
    check_request_uri GET /healthz;
    check_request_body OK;
    check_response_body OK;
    check_response_codes 200 204;
```

Upstream configuration was 

```
    server 172.18.5.50:35292 weight=5;
    server 172.18.27.50:35292 weight=5;
    server 172.18.28.50:35292 weight=5;
    server 172.18.38.50:35292 weight=5;
    server 172.18.39.50:35292 weight=5;
    server 172.18.40.50:35292 weight=5;
    server 172.18.41.50:35292 weight=5;
    server 172.18.154.50:35292 weight=5;
    server 172.18.155.255:35292 weight=5;
```

Endpoint `172.18.155.255` was unavailable (literally doesn't exist). And tested using `for i in {1..1000}; do curl https://domain.internal; done` using those upstream endpoint above. 

Is it expected if I do the curl, I need to wait approx 1-5mins to wait the timeout peers/upstream marked down and the traffic will passed?

**Comment by ZigzagAK** [comment]
Timeout in milliseconds. NOT seconds. timeout=5000
You wrote:
Please down peer after 3 fails with interval 1 second and timeout 5 ms.
You may turn on debug.log to monitoring all checks.

**Comment by draskolnikova** [comment]
@ZigzagAK Trying with `timeout=5000` value, still same. I'll post asciinema for you, hang on.
